# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# SASS/SCSS
sass:
  sass_dir: _scss

# Setup
title:            'Niels Hoppe'
description:      'Another guy with a website.'
url:              http://www.nielshoppe.de
baseurl:          /

author:
  name:           'Niels Hoppe'
  url:            http://www.nielshoppe.de

paginate:         5
paginate_path:    'articles/page/:num'

collections:
  - data

# Custom configuration

languages: # site.languages
  - abbr: DE
  - abbr: EN
  - abbr: FR
