# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Niels Hoppe'
tagline:          'Another guy with a website'
description:      'Another guy with a website.'
url:              http://hielsnoppe.github.io
baseurl:          /

author:
  name:           'Niels Hoppe'
  url:            http://nielshoppe.de

paginate:         5
paginate_path:    'articles/page/:num'
