# Dependencies
markdown: redcarpet
#highlighter: pygments

gems: [jekyll-paginate]

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: 'Niels Hoppe'
description: 'Another guy with a website.'
url: http://www.nielshoppe.de
baseurl: /

author:
  name: 'Niels Hoppe'
  url: http://www.nielshoppe.de

paginate: 5
paginate_path: 'articles/page/:num'

# Custom configuration

destination: /var/www/public
exclude:
  - bower.json
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Vagrantfile

my_theme: my-website-theme
languages: # site.languages
  - abbr: DE
  - abbr: EN
  - abbr: FR

# Theming
layouts_dir: _themes/my-website-theme/dist/_layouts
includes_dir: _themes/my-website-theme/dist/_includes
sass:
  sass_dir: _themes/my-website-theme/dist/_sass
